server:
  port: 3344
spring:
  application:
    name: config
  cloud:
    compatibility-verifier:
      enabled: false
    config:

      server:
        git:
          uri: https://github.com/Fukuaa/config.git
          password: 1464645627abc**
          username: fukuaa
          search-paths:
            config
        bootstrap: true
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
