server:
  port: 3344
spring:
  application:
    name: config
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      label: master
      server:
        git:
          uri: https://github.com/Fukuaa/config.git
          password: 1464645627abc**
          username: fukuaa
          search-paths:
            config
          default-label: master
        bootstrap: true
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'