server:
  port: 3344
spring:
  application:
    name: configcenter
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhengqingfeng/zqf.git
          search-paths:
            - zqf
          password: z123456+
          username: 18771189524
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

