server:
  port: 80
spring:
  application:
    name: newhystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: #http://localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/
