server:
  port: 9002
spring:
  application:
    name: nacos666
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.132:1111
        #weight: 1
#management:
  #endpoints:
    #web:
      #exposure:
        #include: '*'

