server:
  port: 2002
spring:
  application:
    name: storage
  cloud:
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP
    nacos:
      discovery:
        server-addr: http://192.168.23.132:1111
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
