server:
  port: 8002
spring:
  application:
    name: hystrix
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: #http://localhost:7001/eureka/
     defaultZone: http://localhost:7001/eureka/
